name: riak_dart
description: An unofficial Riak client for dart based on Riaks ProtoBuf API.
version: 0.4.0
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
homepage: https://github.com/epnw/riak_dart

environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  protobuf: ^1.0.0
  meta: ^1.1.7
  pedantic: ^1.8.0+1